"""Build the untouched gold set from real, human-written Finglish.

Source: https://github.com/mmahdibarghi/finglish-dataset (MIT). Its Persian
side comes from Mozilla Common Voice Persian (CC0) — the companion file keys
every row to a `common_voice_fa_*.mp3` filename — and the Finglish side was
written by a human annotator for a text-to-speech project.

Why this replaces the previous author-written gold set: the old one was written
by the same author as the rule table, so it tested Finglish that the rules
already handled. This is Finglish someone actually typed, with the colloquial
register (`midouni`, `misheh`, `vaseh`) and the natural spelling inconsistency
that synthetic data cannot fake.

Honest limits, which belong in any citation of a number from this file:
  * It is one annotator, not a panel. Per-writer habits are baked in.
  * It was written for TTS, so it is read-aloud register rather than chat.
  * ~30% of rows are misaligned; only the clean subset is kept, and the
    threshold is deliberately conservative.

This is stage one of two. The word-count filter here cannot see a row whose two
sides have matching word counts and different content; `scripts/split-gold.ts`
quarantines those into `data/gold/gold-misaligned.jsonl` and merges its counts
into the same provenance file. **Running this alone restores them.**

    python -m tiny_finglish_training.build_gold
    node scripts/split-gold.ts --write
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import urllib.request
from pathlib import Path

from .normalize import normalize

BASE = "https://raw.githubusercontent.com/mmahdibarghi/finglish-dataset/main/"
#: (filename, finglish column, persian column, has header)
SOURCES = [
    ("PersianToFinglishDataset.txt", 0, 1, True),
    ("PersianToFinglish-NoT%20match%20sentence.txt", 0, 1, False),
    ("PersianFinglishDataWithVoiceNames.txt", 1, 2, True),
]

LATIN_OK = re.compile(r"^[a-zA-Z0-9 ,.\-'?!:;()’]+$")
PERSIAN_OK = re.compile(r"[؀-ۿ]")


def fetch(name: str) -> str:
    with urllib.request.urlopen(BASE + name, timeout=60) as response:
        return response.read().decode("utf-8")


def build(out: Path, max_word_delta: int = 1, min_words: int = 2, max_words: int = 30) -> dict:
    pairs: dict[str, str] = {}
    raw_rows = 0
    for name, ci, cj, header in SOURCES:
        lines = fetch(name).splitlines()
        if header:
            lines = lines[1:]
        for line in lines:
            parts = line.split("\t")
            if len(parts) <= max(ci, cj):
                continue
            raw_rows += 1
            finglish = parts[ci].strip().strip(".").strip()
            persian = normalize(parts[cj].strip())
            if finglish and persian:
                pairs.setdefault(finglish.lower(), persian)

    kept, dropped = [], {"misaligned": 0, "length": 0, "charset": 0}
    for finglish, persian in sorted(pairs.items()):
        lw, pw = finglish.split(), persian.split()
        if not (min_words <= len(lw) <= max_words):
            dropped["length"] += 1
            continue
        if not LATIN_OK.match(finglish) or not PERSIAN_OK.search(persian):
            dropped["charset"] += 1
            continue
        # The alignment filter. Persian and Finglish word counts should track
        # closely; a large gap means the two sides are not the same sentence,
        # which is the dominant defect in the source.
        if abs(len(lw) - len(pw)) > max_word_delta:
            dropped["misaligned"] += 1
            continue
        kept.append({
            "id": f"gold-{len(kept) + 1:04d}",
            "input": finglish,
            "expected": persian,
            "alternatives": [],
        })

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        for row in kept:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    return {
        "source": "https://github.com/mmahdibarghi/finglish-dataset",
        "sourceLicense": "MIT",
        "persianSideOrigin": "Mozilla Common Voice Persian (CC0)",
        "rawRows": raw_rows,
        "uniquePairs": len(pairs),
        "kept": len(kept),
        "dropped": dropped,
        "filters": {"max_word_delta": max_word_delta, "min_words": min_words, "max_words": max_words},
        "sha256": digest,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[2] / "data" / "gold" / "gold.jsonl")
    parser.add_argument("--provenance", type=Path, default=Path(__file__).resolve().parents[2] / "data" / "provenance" / "gold.json")
    args = parser.parse_args()

    manifest = build(args.out)
    args.provenance.parent.mkdir(parents=True, exist_ok=True)
    args.provenance.write_text(json.dumps(
        {"$comment": "GENERATED by training/tiny_finglish_training/build_gold.py.", **manifest},
        indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))
    print("\nStage two: node scripts/split-gold.ts --write", flush=True)


if __name__ == "__main__":
    main()
