/**
 * Build the committed lexicon artifact from the upstream Hunspell dictionary.
 *
 * Upstream is Lilak fa-IR (Apache-2.0), fetched by `scripts/fetch-lexicon.sh`
 * into `data/lexicon/upstream/`, which is gitignored. What gets committed is
 * the small derived artifact plus a provenance record carrying the upstream
 * SHA-256, so the chain from source to shipped bytes is auditable.
 */
import { brotliCompressSync, constants } from "node:zlib";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { encodeFrontCoded, decodeFrontCoded } from "../src/frontcode.ts";
import { normalize } from "../src/normalize.ts";

const root = new URL("..", import.meta.url);
const dicPath = new URL("data/lexicon/upstream/fa-IR.dic", root);
const raw = readFileSync(dicPath);
const text = raw.toString("utf8");

// Hunspell .dic: a count line, then `stem/FLAGS` per line.
const stems = new Set<string>();
for (const line of text.split("\n").slice(1)) {
  const stem = line.split("/")[0]!.trim();
  if (!stem) continue;
  const normalized = normalize(stem);
  // Keep single-token Persian entries only; the runtime snap tier looks words
  // up, and multi-word entries would never match a single span.
  if (!normalized || /\s/.test(normalized)) continue;
  stems.add(normalized);
}

const words = [...stems].sort();
const encoded = encodeFrontCoded(words);
const compressed = brotliCompressSync(encoded, {
  params: {
    [constants.BROTLI_PARAM_QUALITY]: 11,
    [constants.BROTLI_PARAM_SIZE_HINT]: encoded.length,
  },
});

// Round-trip before committing. A corrupted lexicon would fail silently as a
// slow accuracy regression rather than a crash.
const decoded = decodeFrontCoded(encoded);
if (decoded.length !== words.length || decoded.some((w, i) => w !== words[i])) {
  throw new Error("front-coding round-trip failed");
}

mkdirSync(new URL("data/lexicon", root), { recursive: true });
writeFileSync(new URL("data/lexicon/fa-stems.bin", root), compressed);

const provenance = {
  $comment: "GENERATED by scripts/build-lexicon.ts. Records the chain from upstream source to committed artifact.",
  name: "Lilak, Persian Spell Checking Dictionary",
  version: "fa-IR, via npm dictionary-fa@2.0.0",
  license: "Apache-2.0",
  licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0",
  homepage: "https://github.com/b00f/lilak",
  retrieved: new Date().toISOString().slice(0, 10),
  upstream: {
    file: "data/lexicon/upstream/fa-IR.dic",
    bytes: raw.length,
    sha256: createHash("sha256").update(raw).digest("hex"),
    entries: text.split("\n").length - 1,
  },
  derived: {
    file: "data/lexicon/fa-stems.bin",
    uniqueStems: words.length,
    frontCodedBytes: encoded.length,
    brotliBytes: compressed.length,
    bytesPerWord: +(compressed.length / words.length).toFixed(3),
    sha256: createHash("sha256").update(compressed).digest("hex"),
  },
  notes: [
    "Stems are normalized with src/normalize.ts before deduplication, so the artifact is in the same canonical form as every model output.",
    "Multi-token entries are dropped: the runtime snap tier matches single spans.",
    "Affix rules (fa-IR.aff, 101 rules) are NOT applied here. Expanding them yields ~1.29M surface forms for ~1.2 KiB more Brotli, which is the right trade if M2 decides the lexicon ships.",
    "No frequency ranking is included. See docs/open-items.md: deriving one needs a permissively licensed corpus (MADLAD-400 fa, CC-BY-4.0), which this repository does not vendor.",
  ],
};
writeFileSync(
  new URL("data/provenance/lexicon.json", root),
  `${JSON.stringify(provenance, null, 2)}\n`,
);

const kib = (n: number) => `${(n / 1024).toFixed(1)} KiB`;
console.log(`stems           ${words.length.toLocaleString()}`);
console.log(`front-coded     ${kib(encoded.length)}`);
console.log(`+ brotli        ${kib(compressed.length)}  (${provenance.derived.bytesPerWord} bytes/word)`);
console.log(`round-trip      ok`);
