/**
 * Dump the grapheme table from `src/rules.ts` to `data/rules/graphemes.json`
 * so the Python training code reads exactly the same correspondences.
 *
 * The TypeScript table is the source of truth. The JSON is a generated
 * artifact — it is committed so training runs are reproducible without a Node
 * toolchain, but it must never be hand-edited. CI re-runs this and fails if
 * the checked-in file drifts.
 */
import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { ALL_POSITIONS, CONSONANTS, GRAPHEMES, LATIN_UNITS, SILENT, VOWELS, ZWNJ_RULES } from "../src/rules.ts";

const payload = {
  $comment: "GENERATED by scripts/export-rules.ts from src/rules.ts. Do not edit.",
  version: 1,
  positions: ALL_POSITIONS,
  latinUnits: LATIN_UNITS,
  groups: {
    consonants: CONSONANTS,
    vowels: VOWELS,
    silent: SILENT,
    zwnj: ZWNJ_RULES,
  },
  graphemes: GRAPHEMES,
};

const json = `${JSON.stringify(payload, null, 2)}\n`;
writeFileSync(new URL("../data/rules/graphemes.json", import.meta.url), json);
const hash = createHash("sha256").update(json).digest("hex");
console.log(`data/rules/graphemes.json  ${GRAPHEMES.length} graphemes  ${LATIN_UNITS.length} latin units`);
console.log(`sha256 ${hash}`);
